apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cron
  namespace: default   # ✅ Add this
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - "echo Hello from CronJob! && date"
          restartPolicy: OnFailure
