apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default   # ✅ Add this
  labels:
    app: nginx-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-sample
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
